{{- /*
GENERATED by `make values-schema` from keys.yaml. DO NOT HAND-EDIT.

ConfigMap data: one ANDARA_* line per server configuration key the running binary
reads, emitted only when the values file sets it. A key that is not set is not
rendered, so the server default applies and the chart never restates it (AW-INF-003).
*/ -}}
{{- define "andara.serverEnv" -}}
{{- $v := dig "content" "source" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_SOURCE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "path" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_PATH: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "strict_orphans" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_STRICT_ORPHANS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "http" "port" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_HTTP_PORT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "service_name" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SERVICE_NAME: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "environment" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_ENV: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "log_format" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LOG_FORMAT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "log_level" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LOG_LEVEL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "otlp_endpoint" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_OTLP_ENDPOINT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "listen" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_LISTEN: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "tls_cert_file" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TLS_CERT_FILE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "tls_key_file" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TLS_KEY_FILE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "drain_timeout" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_DRAIN_TIMEOUT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "max_recv_bytes" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_MAX_RECV_BYTES: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "max_request_timeout" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_MAX_REQUEST_TIMEOUT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "protocol" "min_version" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_PROTOCOL_MIN: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "protocol" "max_version" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_PROTOCOL_MAX: {{ $v | toString | quote }}
{{- end }}
{{- end -}}
