{{- /*
GENERATED by `make values-schema` from keys.yaml. DO NOT HAND-EDIT.

ConfigMap data: one ANDARA_* line per server configuration key the running binary
reads, emitted only when the values file sets it. A key that is not set is not
rendered, so the server default applies and the chart never restates it (AW-INF-003).
*/ -}}
{{- define "andara.serverEnv" -}}
{{- $v := dig "content" "source" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_SOURCE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "path" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_PATH: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "strict_orphans" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_STRICT_ORPHANS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "http" "port" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_HTTP_PORT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "service_name" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SERVICE_NAME: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "environment" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_ENV: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "log_format" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LOG_FORMAT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "log_level" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LOG_LEVEL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "otlp_endpoint" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_OTLP_ENDPOINT: {{ $v | toString | quote }}
{{- end }}
{{- end -}}
