{{- /*
GENERATED by `make values-schema` from keys.yaml. DO NOT HAND-EDIT.

ConfigMap data: one ANDARA_* line per server configuration key the running binary
reads, emitted only when the values file sets it. A key that is not set is not
rendered, so the server default applies and the chart never restates it (AW-INF-003).
*/ -}}
{{- define "andara.serverEnv" -}}
{{- $v := dig "content" "source" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_SOURCE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "path" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_PATH: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "strict_orphans" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_STRICT_ORPHANS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "http" "port" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_HTTP_PORT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "service_name" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SERVICE_NAME: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "environment" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_ENV: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "log_format" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LOG_FORMAT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "log_level" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LOG_LEVEL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "otlp_endpoint" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_OTLP_ENDPOINT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "trace_sample_ratio" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TRACE_SAMPLE_RATIO: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "telemetry" "trust_inbound_traceparent" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TRUST_INBOUND_TRACEPARENT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "source" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SIM_SOURCE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "tick_rate" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TICK_RATE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "tick_budget_ms" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TICK_BUDGET_MS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "max_per_tick" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_MAX_PER_TICK: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "drain_timeout_ms" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_DRAIN_TIMEOUT_MS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "seed" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SIM_SEED: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "sim" "checkpoint_every_ticks" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CHECKPOINT_EVERY_TICKS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "command" "max_intent_bytes" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_MAX_INTENT_BYTES: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "command" "verb_table_path" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_VERB_TABLE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "listen" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_LISTEN: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "tls_cert_file" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TLS_CERT_FILE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "tls_key_file" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_TLS_KEY_FILE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "drain_timeout" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_DRAIN_TIMEOUT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "max_recv_bytes" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_MAX_RECV_BYTES: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "grpc" "max_request_timeout" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_GRPC_MAX_REQUEST_TIMEOUT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "protocol" "min_version" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_PROTOCOL_MIN: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "protocol" "max_version" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_PROTOCOL_MAX: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "events" "subscriber_buffer" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SUBSCRIBER_BUFFER: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "events" "max_subscribers" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_MAX_SUBSCRIBERS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "egress" "buffer" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_EGRESS_BUFFER: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "egress" "resume_window" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_EGRESS_RESUME_WINDOW: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "egress" "heartbeat_interval" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_HEARTBEAT_INTERVAL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "rate_limit" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_INGRESS_RATE_LIMIT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "burst" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_INGRESS_BURST: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "produce_deadline" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_PRODUCE_DEADLINE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "max_pending" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_INGRESS_MAX_PENDING: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "agent_rate_limit" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AGENT_RATE_LIMIT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "transit_hold" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_INGRESS_TRANSIT_HOLD: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "ingress" "idempotency_window" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_INGRESS_IDEMPOTENCY_WINDOW: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "interval" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_INTERVAL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "max_stall_ms" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_MAX_STALL_MS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "store" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_STORE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "fs_path" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_FS_PATH: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "s3_bucket" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_S3_BUCKET: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "s3_endpoint" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_S3_ENDPOINT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "snapshot" "upload_timeout" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_SNAPSHOT_UPLOAD_TIMEOUT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "kafka" "brokers" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_KAFKA_BROKERS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "store" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_STORE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "session_ttl" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_SESSION_TTL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "refresh_ttl" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_REFRESH_TTL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "token_key_file" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_TOKEN_KEY_FILE: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "argon2" "memory_kib" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_ARGON2_MEMORY_KIB: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "argon2" "time" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_ARGON2_TIME: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "argon2" "threads" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_ARGON2_THREADS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "rate_limit" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_RATE_LIMIT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "invite_ttl" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_INVITE_TTL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "recheck_interval" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_RECHECK_INTERVAL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "k8s_issuer" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_K8S_ISSUER: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "auth" "k8s_jwks_url" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_AUTH_K8S_JWKS_URL: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "character" "max_per_account" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CHARACTER_MAX_PER_ACCOUNT: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "character" "spawn_room" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CHARACTER_SPAWN_ROOM: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "character" "name_pattern" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CHARACTER_NAME_PATTERN: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "session" "linkdead_max" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_LINKDEAD_MAX: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "packs" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_PACKS: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "cache_dir" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_CACHE_DIR: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "max_blob_bytes" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_MAX_BLOB_BYTES: {{ $v | toString | quote }}
{{- end }}
{{- $v := dig "content" "reload_debounce" "__unset__" (.Values.server | default dict) }}
{{- if not (eq (toString $v) "__unset__") }}
ANDARA_CONTENT_RELOAD_DEBOUNCE: {{ $v | toString | quote }}
{{- end }}
{{- end -}}
