// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Valesor Development

package lang

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	contentv1 "github.com/valesordev/andara/gen/go/andara/content/v1"
)

// corpusDir is the AW-CLI-005 conformance corpus. The tests here are the same
// check `make content-conformance` runs; it is in `make test` as well so that a
// change to the compiler fails on the developer's machine at the same moment it
// would fail in CI.
const corpusDir = "../../docs/specs/content-language/v1/corpus"

// TestConformance is AC-1. Every valid pair matches byte for byte, every
// invalid pair matches its .errors sidecar, and the round-trip pairs are
// identity.
func TestConformance(t *testing.T) {
	rep, err := Conformance(corpusDir)
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range rep.Cases {
		if c.OK || c.Skipped {
			continue
		}
		t.Errorf("%s:\n  %s", c.Case, strings.Join(c.Reasons, "\n  "))
	}
	if rep.Passed == 0 {
		t.Fatal("no cases ran; the corpus path is wrong")
	}
	t.Logf("%d cases pass, %d skipped as pending", rep.Passed, rep.Skipped)
}

// TestConformanceIsNotVacuous breaks the compiler and asserts the corpus
// notices. A conformance suite that cannot be made to fail has not been shown
// to check anything, and this one compares generated bytes against hand-written
// ones — exactly the shape that passes for the wrong reason when the comparison
// is misrouted.
func TestConformanceIsNotVacuous(t *testing.T) {
	out, ds := Compile(filepath.Join(corpusDir, "valid", "merge-three-deep"), corpusCore(t), nil)
	if out == nil {
		t.Fatalf("expected a compile: %v", ds)
	}
	beast := templateNamed(t, out, "p.Beast")

	// Beast inherits Behavior.name from Creature and declares Memory itself.
	// Dropping the inherited Component is the merge bug the case exists to
	// catch, so the expected bytes must stop matching when it is dropped.
	before := string(CanonicalJSON(beast))
	beast.Components = beast.Components[1:]
	if after := string(CanonicalJSON(beast)); after == before {
		t.Fatal("dropping a merged Component changed no bytes; the comparison is not reading the Components")
	}
	if !strings.Contains(before, "andara.core.Behavior") {
		t.Error("p.Beast does not carry the Component it inherits from p.Creature")
	}
}

// TestCoreSeedIsReproducible is the first of the corpus's two anchors: the
// compiler's output for corpus/valid/core/ is byte-identical to the shipped
// andara.core seed, which TestCoreSeedMatchesFixture holds from the other side.
// It is what stops the corpus from being a description of whatever its author
// imagined.
func TestCoreSeedIsReproducible(t *testing.T) {
	out, ds := Compile(filepath.Join(corpusDir, "valid", "core"), nil, nil)
	if out == nil {
		t.Fatalf("corpus/valid/core does not compile: %v", ds)
	}
	if len(out.Templates) != 4 {
		t.Fatalf("got %d Templates, want 4", len(out.Templates))
	}
	for _, tmpl := range out.Templates {
		want, err := os.ReadFile(filepath.Join("../core/templates", tmpl.GetName()+".json"))
		if err != nil {
			t.Fatal(err)
		}
		if got := CanonicalJSON(tmpl); string(got) != string(want) {
			t.Errorf("%s differs from the shipped seed:\n--- got ---\n%s\n--- want ---\n%s", tmpl.GetName(), got, want)
		}
	}
}

// TestTownAnchorMatchesLoaderFixtures is the second anchor: the Templates
// AW-SRV-022's loader fixtures already hold.
func TestTownAnchorMatchesLoaderFixtures(t *testing.T) {
	out, ds := Compile(filepath.Join(corpusDir, "valid", "town"), corpusCore(t), nil)
	if out == nil {
		t.Fatalf("corpus/valid/town does not compile: %v", ds)
	}
	for _, tmpl := range out.Templates {
		path := filepath.Join("../../testdata/templates/templates", tmpl.GetName()+".json")
		want, err := os.ReadFile(path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			t.Fatal(err)
		}
		if got := CanonicalJSON(tmpl); string(got) != string(want) {
			t.Errorf("%s differs from %s:\n--- got ---\n%s\n--- want ---\n%s", tmpl.GetName(), path, got, want)
		}
	}
}

// TestFormatIsIdempotent is AC-3 and formatting.md AC-1: a second run of fmt
// changes nothing, over every .aw in the corpus.
func TestFormatIsIdempotent(t *testing.T) {
	for _, path := range corpusSources(t) {
		src, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		once, ds := Format(src)
		if len(ds) > 0 {
			if strings.Contains(path, "invalid/syntax") || strings.Contains(path, "invalid/encoding") {
				continue // these do not parse, by construction
			}
			t.Errorf("%s: %v", path, ds[0])
			continue
		}
		twice, ds := Format(once)
		if len(ds) > 0 {
			t.Errorf("%s: formatted output does not re-parse: %v", path, ds[0])
			continue
		}
		if string(once) != string(twice) {
			t.Errorf("%s: fmt is not idempotent:\n--- once ---\n%s\n--- twice ---\n%s", path, once, twice)
		}
	}
}

// TestCorpusIsFormatted is formatting.md AC-2: every .aw a Builder would read
// is already fmt-clean, so `content fmt --check` over the corpus exits 0.
func TestCorpusIsFormatted(t *testing.T) {
	for _, path := range corpusSources(t) {
		if strings.Contains(path, "invalid/syntax") || strings.Contains(path, "invalid/encoding") {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		got, ds := Format(src)
		if len(ds) > 0 {
			t.Errorf("%s: %v", path, ds[0])
			continue
		}
		if string(got) != string(src) {
			t.Errorf("%s is not fmt-clean:\n--- want ---\n%s\n--- got ---\n%s", path, src, got)
		}
	}
}

// TestFormatDoesNotReorder is formatting.md AC-4, the load-bearing decision in
// that document. A Builder who lays out a Zone as the walk through it keeps
// that layout, and the compiled output is sorted regardless.
func TestFormatDoesNotReorder(t *testing.T) {
	src := []byte(`zone z "Z" {
  room plaza "Plaza" {
    exit north -> lane
    exit east -> alley
  }

  room lane "Lane" {
    exit south -> plaza
  }

  room alley "Alley" {
    exit west -> plaza
  }
}
`)
	got, ds := Format(src)
	if len(ds) > 0 {
		t.Fatal(ds[0])
	}
	if string(got) != string(src) {
		t.Errorf("fmt reordered a Zone:\n--- want ---\n%s\n--- got ---\n%s", src, got)
	}
	// ... and the compiled output is sorted regardless.
	dir := t.TempDir()
	write(t, filepath.Join(dir, "pack.aw"), "pack p requires andara.core@1\n")
	write(t, filepath.Join(dir, "z.aw"), string(src))
	out, ds := Compile(dir, corpusCore(t), nil)
	if out == nil {
		t.Fatalf("compile: %v", ds)
	}
	rooms := out.Zones[0].GetRooms()
	if rooms[0].GetId() != "alley" || rooms[1].GetId() != "lane" || rooms[2].GetId() != "plaza" {
		t.Errorf("compiled Rooms are not sorted by id: %s, %s, %s", rooms[0].GetId(), rooms[1].GetId(), rooms[2].GetId())
	}
	exits := rooms[2].GetExits()
	if exits[0].GetDirection() != "east" || exits[1].GetDirection() != "north" {
		t.Errorf("compiled Exits are not sorted by direction string: %s, %s", exits[0].GetDirection(), exits[1].GetDirection())
	}
}

// TestCompileIsOrderIndependent is semantics.md §2: neither the order of files
// in a pack nor the order of declarations within a file affects the compiled
// output.
func TestCompileIsOrderIndependent(t *testing.T) {
	one := t.TempDir()
	write(t, filepath.Join(one, "pack.aw"), "pack p requires andara.core@1\n")
	write(t, filepath.Join(one, "a.aw"), "template Wolf extends Beast {}\n")
	write(t, filepath.Join(one, "b.aw"), "template Beast kind entity {}\n")

	two := t.TempDir()
	write(t, filepath.Join(two, "pack.aw"), "pack p requires andara.core@1\n")
	write(t, filepath.Join(two, "z.aw"), "template Beast kind entity {}\ntemplate Wolf extends Beast {}\n")

	a, ds := Compile(one, corpusCore(t), nil)
	if a == nil {
		t.Fatalf("compile: %v", ds)
	}
	b, ds := Compile(two, corpusCore(t), nil)
	if b == nil {
		t.Fatalf("compile: %v", ds)
	}
	for i := range a.Templates {
		// Names differ by temp directory, so compare the parts that should not.
		ja := string(CanonicalJSON(a.Templates[i]))
		jb := string(CanonicalJSON(b.Templates[i]))
		// SourceRef legitimately differs — different files, different lines.
		ja, jb = stripSource(ja), stripSource(jb)
		if ja != jb {
			t.Errorf("declaration order changed the output:\n--- a ---\n%s\n--- b ---\n%s", ja, jb)
		}
	}
}

func stripSource(s string) string {
	i := strings.Index(s, `"source"`)
	if i < 0 {
		return s
	}
	return s[:i]
}

// TestOfflineCompileUsesTheCache is AC-5: a cached andara.core@1 compiles with
// no network, and no cache at all is core_version_mismatch telling the Builder
// to run `content fetch-core` rather than a missing-file error.
func TestOfflineCompileUsesTheCache(t *testing.T) {
	core := corpusCore(t)
	root := t.TempDir()
	if err := WriteCachedPack(root, core); err != nil {
		t.Fatal(err)
	}
	got, ok, err := LoadCachedPack(root, CorePack, 1)
	if err != nil || !ok {
		t.Fatalf("cache read: ok=%v err=%v", ok, err)
	}
	if len(got.Templates) != len(core.Templates) {
		t.Fatalf("cache holds %d Templates, want %d", len(got.Templates), len(core.Templates))
	}

	pack := t.TempDir()
	write(t, filepath.Join(pack, "pack.aw"), "pack p requires andara.core@1\n")
	write(t, filepath.Join(pack, "t.aw"), "template Merchant extends andara.core.Npc {}\n")
	if out, ds := Compile(pack, got, nil); out == nil {
		t.Fatalf("offline compile failed: %v", ds)
	}

	// No cache: the finding names both versions and the command to run.
	_, ds := Compile(pack, nil, nil)
	if len(ds) != 1 || ds[0].Code != CodeCoreVersionMismatch {
		t.Fatalf("want one core_version_mismatch, got %v", ds)
	}
	if !strings.Contains(ds[0].Message, "fetch-core") {
		t.Errorf("the message does not say what to run: %q", ds[0].Message)
	}
}

// TestCoreVersionMismatchNamesBoth is AC-6, in its own numbers: a pack
// declaring `requires andara.core@4` against a cache of @3.
func TestCoreVersionMismatchNamesBoth(t *testing.T) {
	cached := corpusCore(t)
	cached.Version = 3

	pack := t.TempDir()
	write(t, filepath.Join(pack, "pack.aw"), "pack p requires andara.core@4\n")

	_, ds := Compile(pack, cached, nil)
	if len(ds) != 1 || ds[0].Code != CodeCoreVersionMismatch {
		t.Fatalf("want core_version_mismatch, got %v", ds)
	}
	if !strings.Contains(ds[0].Message, "@4") || !strings.Contains(ds[0].Message, "@3") {
		t.Errorf("the finding must name both versions; it says %q", ds[0].Message)
	}
	// AC-5's cached case, from the other side: @3 required against @3 compiles.
	write(t, filepath.Join(pack, "pack.aw"), "pack p requires andara.core@3\n")
	if out, ds := Compile(pack, cached, nil); out == nil {
		t.Errorf("a matching cache did not satisfy the requirement: %v", ds)
	}
}

// TestPackMismatchNeedsTheCallersPackName records the shape of the one finding
// Compile cannot raise from a directory alone: a pack directory's name is not
// its pack name, so "the pack being compiled" is an input.
func TestPackMismatchNeedsTheCallersPackName(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "pack.aw"), "pack elsewhere requires andara.core@1\n")

	if _, ds := Compile(dir, corpusCore(t), nil); len(ds) != 0 {
		t.Errorf("with no expected pack, the declaration stands: %v", ds)
	}
	_, ds := CompileOpts(dir, corpusCore(t), nil, Options{Pack: "town"})
	if len(ds) != 1 || ds[0].Code != CodePackMismatch {
		t.Fatalf("want pack_mismatch, got %v", ds)
	}
	if ds[0].Col != 6 {
		t.Errorf("pack_mismatch points at column %d; the declared name starts at 6", ds[0].Col)
	}
}

// TestWarningsDoNotFailACompile is errors.md rule 7.
func TestWarningsDoNotFailACompile(t *testing.T) {
	out, ds := Compile(filepath.Join(corpusDir, "valid", "warn-orphan-room"), corpusCore(t), nil)
	if out == nil {
		t.Fatalf("a warning refused the compile: %v", ds)
	}
	if len(ds) != 1 || ds[0].Severity != SeverityWarning || ds[0].Code != CodeOrphanRoom {
		t.Fatalf("want one orphan_room warning, got %v", ds)
	}
	if HasError(ds) {
		t.Error("HasError is true for a warning-only compile")
	}
}

// TestSourceBlobsArePublishedVerbatim is semantics.md §6: a pack publishes its
// .aw sources alongside the compiled output, byte for byte as authored, which
// is what makes `content fetch` return the comments that compile drops.
func TestSourceBlobsArePublishedVerbatim(t *testing.T) {
	dir := filepath.Join(corpusDir, "valid", "town")
	out, ds := Compile(dir, corpusCore(t), nil)
	if out == nil {
		t.Fatalf("compile: %v", ds)
	}
	var found int
	for _, b := range out.Blobs {
		if b.MediaType != SourceMediaType {
			continue
		}
		found++
		want, err := os.ReadFile(filepath.Join(dir, strings.TrimPrefix(b.Path, SourcePrefix)))
		if err != nil {
			t.Fatal(err)
		}
		if string(b.Bytes) != string(want) {
			t.Errorf("%s is not the authored bytes", b.Path)
		}
		if !strings.HasPrefix(b.Path, SourcePrefix) {
			t.Errorf("%s is not under %s", b.Path, SourcePrefix)
		}
	}
	if found != 6 {
		t.Errorf("published %d source blobs, want 6", found)
	}
	// Comments survive publication even though compile drops them.
	for _, b := range out.Blobs {
		if b.Path == SourcePrefix+"npcs.aw" && !strings.Contains(string(b.Bytes), "// The people of the town.") {
			t.Error("the published source lost its comments")
		}
	}
}

func corpusCore(t *testing.T) *Pack {
	t.Helper()
	out, ds := Compile(filepath.Join(corpusDir, "valid", "core"), nil, nil)
	if out == nil {
		t.Fatalf("corpus/valid/core does not compile: %v", ds)
	}
	return &Pack{Name: CorePack, Version: 1, Templates: out.Templates}
}

func templateNamed(t *testing.T, out *Output, name string) *contentv1.TemplateDefinition {
	t.Helper()
	for _, tmpl := range out.Templates {
		if tmpl.GetName() == name {
			return tmpl
		}
	}
	t.Fatalf("no Template %q", name)
	return nil
}

func corpusSources(t *testing.T) []string {
	t.Helper()
	var out []string
	err := filepath.WalkDir(corpusDir, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(p, ".aw") {
			out = append(out, p)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func write(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestFormatWhitespaceRules is formatting.md §2 and §5: two-space indent, never
// a tab, exactly one LF at the end, a blank line immediately after `{` or
// immediately before `}` removed, and a run of blank lines collapsed to one.
func TestFormatWhitespaceRules(t *testing.T) {
	src := []byte("zone z \"Z\" {\n\n  room a \"A\" {\n\n\t\texit north -> b\n\n\n  }\n\n\n  room b \"B\" {\n    exit south -> a\n\n  }\n\n}\n")
	want := "zone z \"Z\" {\n  room a \"A\" {\n    exit north -> b\n  }\n\n  room b \"B\" {\n    exit south -> a\n  }\n}\n"

	got, ds := Format(src)
	if len(ds) > 0 {
		t.Fatal(ds[0])
	}
	if string(got) != want {
		t.Errorf("fmt output:\n%q\nwant:\n%q", got, want)
	}
	if strings.Contains(string(got), "\t") {
		t.Error("fmt emitted a tab")
	}
	if !strings.HasSuffix(string(got), "}\n") || strings.HasSuffix(string(got), "\n\n") {
		t.Error("the file does not end in exactly one LF")
	}
	for _, line := range strings.Split(string(got), "\n") {
		if line != strings.TrimRight(line, " \t") {
			t.Errorf("trailing whitespace on %q", line)
		}
	}
}

// TestFormatPreservesComments is formatting.md §5. A comment is the one thing
// in the file the formatter has no way to understand, so it does the minimum
// that keeps indentation honest: re-indent an own-line comment, keep a trailing
// one on its line separated by two spaces, and never move one across a
// declaration.
func TestFormatPreservesComments(t *testing.T) {
	src := []byte("// A file header.\n//\n// With a blank comment line in it.\n\n// The Zone's own note.\nzone market \"The Market\" {\n  // The square is the spawn Room.\n  room square \"Market Square\" {\n    exit east -> pier  // cross-Zone\n  }\n}\n")
	got, ds := Format(src)
	if len(ds) > 0 {
		t.Fatal(ds[0])
	}
	if string(got) != string(src) {
		t.Errorf("fmt moved a comment:\n--- got ---\n%s\n--- want ---\n%s", got, src)
	}

	// ... and compile drops them, because there is no field to hold them
	// (semantics.md §1). The source blob is what carries them to publication.
	dir := t.TempDir()
	write(t, filepath.Join(dir, "pack.aw"), "pack p requires andara.core@1\n")
	write(t, filepath.Join(dir, "z.aw"), "// a comment\nzone z \"Z\" {\n  room r \"R\" {}\n}\n")
	out, ds := Compile(dir, corpusCore(t), nil)
	if out == nil {
		t.Fatalf("compile: %v", ds)
	}
	for _, b := range out.Blobs {
		if b.MediaType == BlobMediaType && strings.Contains(string(b.Bytes), "a comment") {
			t.Errorf("a comment reached the compiled blob %s", b.Path)
		}
	}
}
