#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Valesor Development

"""The Builder's Guide's two machine-checked promises (AW-INF-028, AW-INF-023 AC-1 and AC-2).

  builder_guide.py reference         make builder-reference
      write docs/builders/reference.md from `andara-cli content reference --output json`
  builder_guide.py reference-check   make builder-reference-check
      fail when that file differs from what `reference` would write, or is missing
  builder_guide.py guide-check       make guide-check
      every `andara-cli` command in the guide exists, every diagnostic code is documented in
      both directions, and every relative link and anchor resolves

`reference.md` is a generated file (CLAUDE.md §2): only `reference` writes it, and whichever PR
changes its source commits the result.

Both targets build `andara-cli` from the working tree into a temporary directory, so neither reads
one from PATH or from ~/.config, and the CLI runs with an empty HOME. `--cli BIN` replaces the
build; the tests use it with a fake.

The command path of a guide line comes from the binary, not from how the words are spelled: each
word extends the path only while Cobra's hidden `__complete` lists it as a subcommand, and flags
and their values are skipped, because `__complete` parses them against the real flag set. A group
(a command with subcommands) followed by a word that isn't one is a typo (`content bogus`). A
leaf takes positionals.

Exit codes: 0 ok; 1 a check failed or the build or CLI did; 2 docs/builders/ doesn't exist.
Findings go to stderr, one per line, prefixed `builder-reference:` or `guide-check:`; the
`guide-check` summary goes to stdout.
"""

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

GUIDE = "docs/builders"
REFERENCE = "docs/builders/reference.md"
ERRORS = "docs/specs/content-language/v1/errors.md"
# From docs/builders/, the heading `## 3. The codes` in errors.md.
ERRORS_LINK = "../specs/content-language/v1/errors.md#3-the-codes"
GENERATED = ("<!-- GENERATED by make builder-reference from `andara-cli content reference --output json`. "
             "DO NOT HAND-EDIT. -->")


class Fail(Exception):
    """A finding that ends the run: printed as `<prefix>: <message>`, exit 1."""


def run(cmd, env=None, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, env=env, **kw)


def build_cli(root, tmp):
    out = os.path.join(tmp, "andara-cli")
    r = run([os.environ.get("GO", "go"), "build", "-o", out, "./cmd/andara-cli"], cwd=root)
    if r.returncode != 0:
        raise Fail("go build ./cmd/andara-cli failed: " + r.stderr.strip()[-400:])
    return out


def clean_env(tmp):
    home = os.path.join(tmp, "home")
    os.makedirs(home, exist_ok=True)
    return {"PATH": os.environ.get("PATH", ""), "HOME": home, "XDG_CONFIG_HOME": home,
            "XDG_STATE_HOME": home, "NO_COLOR": "1"}


# --- builder-reference -------------------------------------------------------------------

def reference_json(cli, env):
    r = run([cli, "content", "reference", "--output", "json"], env=env)
    if r.returncode != 0:
        raise Fail("`andara-cli content reference --output json` exited %d: %s"
                   % (r.returncode, r.stderr.strip()[-400:]))
    try:
        data = json.loads(r.stdout)
    except ValueError as e:
        raise Fail("`content reference` printed no JSON object: %s" % e)
    if data.get("format_version") != 1:
        raise Fail("unsupported format_version %s" % data.get("format_version"))
    return data


def render_reference(data):
    """The four sections, in the JSON's order. Unknown keys are ignored (AC-4)."""
    core = data["core"]
    out = [GENERATED, "", "# Reference", "",
           "[← The Builder's Guide](README.md)", "",
           "## Directions", "",
           "| Direction | Reverse |", "|-----------|---------|"]
    for d in data["directions"]:
        out.append("| `%s` | `%s` |" % (d["name"], d["reverse"]))
    out += ["", "## Component types", "", "| Type | Field | Kind |", "|------|-------|------|"]
    for c in data["component_types"]:
        fields = c.get("fields") or []
        if not fields:
            out.append("| `%s` | none | none |" % c["type"])
        for f in fields:
            out.append("| `%s` | `%s` | %s |" % (c["type"], f["name"], f["kind"]))
    out += ["", "## `%s@%s` Templates" % (core["pack"], core["version"]), "",
            "| Template | Kind | Chain |", "|----------|------|-------|"]
    for t in core["templates"]:
        out.append("| `%s` | %s | %s |" % (t["name"], t["kind"], " › ".join("`%s`" % n for n in t["chain"])))
    out += ["", "## Diagnostics", "", "| Code | Severity | Raised by |", "|------|----------|-----------|"]
    for d in data["diagnostics"]:
        out.append("| [`%s`](%s) | %s | %s |" % (d["code"], ERRORS_LINK, d["severity"], d["raised_by"]))
    return "\n".join(out) + "\n"


def cmd_reference(root, cli, tmp, check):
    cli = cli or build_cli(root, tmp)
    text = render_reference(reference_json(cli, clean_env(tmp)))
    path = Path(root, REFERENCE)
    if check:
        if not path.exists() or path.read_text() != text:
            raise Fail("stale; run make builder-reference")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print("builder-reference: wrote %s" % REFERENCE)
    return 0


# --- guide-check -------------------------------------------------------------------------

FENCE = re.compile(r"^\s*(```+|~~~+)")
LINK = re.compile(r"(?<!\!)\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
SCHEME = re.compile(r"^([a-z][a-z0-9+.-]*:|//)", re.I)
CODE_ROW = re.compile(r"^\|\s*(?:\[)?`([a-z][a-z0-9_]*)`")


def md_files(guide):
    return sorted(p for p in Path(guide).rglob("*.md"))


def split_blocks(text):
    """(code lines with 1-based numbers, prose lines with 1-based numbers). Fences don't nest."""
    code, prose, fence = [], [], None
    for n, line in enumerate(text.splitlines(), 1):
        m = FENCE.match(line)
        if m and (fence is None or line.strip().startswith(fence)):
            fence = None if fence else m.group(1)[:3]
            continue
        (code if fence else prose).append((n, line))
    return code, prose


def joined_commands(code_lines):
    """`andara-cli …` lines, with backslash continuations joined; the first line's number."""
    out, i = [], 0
    while i < len(code_lines):
        n, line = code_lines[i]
        text = line.strip()
        text = text[2:].lstrip() if text.startswith("$ ") else text
        if text.startswith("andara-cli ") or text == "andara-cli":
            while text.endswith("\\") and i + 1 < len(code_lines):
                i += 1
                text = text[:-1].rstrip() + " " + code_lines[i][1].strip()
            out.append((n, text))
        i += 1
    return out


class Completer:
    def __init__(self, cli, env):
        self.cli, self.env, self.cache = cli, env, {}

    def ask(self, words, to_complete):
        key = (tuple(words), to_complete)
        if key not in self.cache:
            r = run([self.cli, "__complete", *words, to_complete], env=self.env)
            names = []
            for line in r.stdout.splitlines():
                if line.startswith(":"):
                    break
                names.append(line.split("\t")[0])
            self.cache[key] = names
        return self.cache[key]

    def resolve(self, words):
        """(path, first unresolved word or None, positional leftovers, is_group)."""
        path, consumed, leftover = [], [], []
        ctx = []
        ended = False
        for w in words:
            if w.startswith("-"):
                consumed.append(w)
                continue
            # A command context lists flags for "-"; a pending flag value doesn't, so the word
            # is that flag's value, not a subcommand or a positional.
            if not any(c.startswith("-") for c in self.ask(consumed, "-")):
                consumed.append(w)
                continue
            if not ended and w in self.ask(consumed, ""):
                path.append(w)
                consumed.append(w)
                continue
            if not ended:
                ctx = list(consumed)  # the command the path resolved to, with its flags
            ended = True
            leftover.append(w)
            consumed.append(w)
        group = bool(leftover) and bool(self.ask(ctx, ""))
        return path, (leftover[0] if leftover else None), leftover, group


def check_command(comp, cli, env, words):
    """None when the line is fine, else the words that name the missing command."""
    path, first_bad, leftover, group = comp.resolve(words)
    if group and leftover:
        return ["andara-cli", *path, first_bad]
    r = run([cli, *path, "--help"], env=env)
    if r.returncode != 0:
        return ["andara-cli", *path]
    return None


def slug(heading, seen):
    s = re.sub(r"[`*]", "", heading.strip().lower())
    s = re.sub(r"[^\w\- ]", "", s).replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else "%s-%d" % (s, n)


def anchors(path):
    code, prose = split_blocks(Path(path).read_text())
    seen, out = {}, set()
    for _, line in prose:
        # An explicit <a id="x"> or <a name="x"> is an anchor GitHub honors, and it's not part of
        # the heading's own slug.
        out.update(re.findall(r'<a\s+(?:id|name)="([^"]+)"', line))
        m = re.match(r"^#{1,6}\s+(.*?)\s*#*\s*$", line)
        if m:
            out.add(slug(re.sub(r"<[^>]+>", "", m.group(1)), seen))
    return out


def errors_codes(path):
    codes, in_codes = [], False
    for line in Path(path).read_text().splitlines():
        if line.startswith("## "):
            in_codes = line.startswith("## 3.")
            continue
        if in_codes:
            m = CODE_ROW.match(line)
            if m:
                codes.append(m.group(1))
    return codes


def reference_codes(path):
    codes, in_diag = [], False
    for line in Path(path).read_text().splitlines():
        if line.startswith("## "):
            in_diag = line.strip() == "## Diagnostics"
            continue
        if in_diag:
            m = CODE_ROW.match(line)
            if m:
                codes.append(m.group(1))
    return codes


def cmd_guide_check(root, cli, tmp):
    guide = Path(root, GUIDE)
    if not guide.is_dir():
        print("guide-check: %s doesn't exist" % GUIDE, file=sys.stderr)
        return 2
    findings = []
    files = md_files(guide)
    commands = links = 0
    cli_ready = None

    for f in files:
        rel = f.relative_to(root)
        code, prose = split_blocks(f.read_text())
        for n, text in joined_commands(code):
            if cli_ready is None:
                cli = cli or build_cli(root, tmp)
                cli_ready = (Completer(cli, clean_env(tmp)), clean_env(tmp))
            try:
                words = shlex.split(re.split(r"\s(?:\||>|>>|&&|;)\s|\s#", text)[0])[1:]
            except ValueError:
                words = text.split()[1:]
            commands += 1
            bad = check_command(cli_ready[0], cli, cli_ready[1], words)
            if bad:
                findings.append('%s:%d: no command "%s"' % (rel, n, " ".join(bad)))
        for n, line in prose:
            line = re.sub(r"`[^`]*`", "", line)
            for m in LINK.finditer(line):
                target = m.group(1)
                if SCHEME.match(target):
                    continue
                links += 1
                file_part, _, frag = target.partition("#")
                dest = f if not file_part else (f.parent / file_part)
                ok = dest.exists()
                if ok and frag and dest.is_file() and dest.suffix == ".md":
                    ok = frag in anchors(dest)
                if not ok:
                    findings.append("%s:%d: broken link %s" % (rel, n, target))

    codes = 0
    ref, errs = Path(root, REFERENCE), Path(root, ERRORS)
    if ref.exists():
        if not errs.exists():
            findings.append("%s not found, so the reference's codes can't be checked" % ERRORS)
        else:
            in_ref, in_err = set(reference_codes(ref)), set(errors_codes(errs))
            codes = len(in_ref | in_err)
            for c in sorted(in_err - in_ref):
                findings.append("code %s is in errors.md but not the reference" % c)
            for c in sorted(in_ref - in_err):
                findings.append("code %s is in the reference but not errors.md" % c)

    for line in findings:
        print("guide-check: " + line, file=sys.stderr)
    if findings:
        return 1
    print("guide-check: %d commands, %d codes, %d links ok" % (commands, codes, links))
    return 0


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("action", choices=["reference", "reference-check", "guide-check"])
    ap.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    ap.add_argument("--cli", help="an andara-cli to use instead of building one (tests)")
    a = ap.parse_args(argv)
    prefix = "guide-check" if a.action == "guide-check" else "builder-reference"
    with tempfile.TemporaryDirectory() as tmp:
        try:
            if a.action == "guide-check":
                return cmd_guide_check(a.root, a.cli, tmp)
            return cmd_reference(a.root, a.cli, tmp, check=(a.action == "reference-check"))
        except Fail as e:
            print("%s: %s" % (prefix, e), file=sys.stderr)
            return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
