#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Valesor Development

"""The Builder's Guide's two machine-checked promises (AW-INF-028, AW-INF-023 AC-1 and AC-2).

  builder_guide.py reference         make builder-reference
      write docs/builders/reference.md from `andara-cli content reference --output json`
  builder_guide.py reference-check   make builder-reference-check
      fail when that file differs from what `reference` would write, or is missing
  builder_guide.py guide-check       make guide-check
      every `andara-cli` command in the guide exists, every diagnostic code is documented in
      both directions, and every relative link and anchor resolves

`reference.md` is a generated file (CLAUDE.md §2): only `reference` writes it, and whichever PR
changes its source commits the result.

Both targets build `andara-cli` from the working tree into a temporary directory, so neither reads
one from PATH or from ~/.config, and the CLI runs with an empty HOME. `--cli BIN` replaces the
build; the tests use it with a fake.

The command path of a guide line comes from the binary, not from how the words are spelled: each
word extends the path only while Cobra's hidden `__complete` lists it as a subcommand, and flags
and their values are skipped, because `__complete` parses them against the real flag set. A group
(a command with subcommands) followed by a word that isn't one is a typo (`content bogus`). A
leaf takes positionals.

Known limits of that resolution, left as they are: an unknown flag doesn't fail a line (only
`<path> --help` is run, and Cobra accepts it), words after `--` or after a bare `--help` count as
flag values, and `-ojson` (no space) isn't parsed by `__complete`.

Exit codes: 0 ok; 1 a check failed or the build or CLI did; 2 docs/builders/ doesn't exist.
Findings go to stderr, one per line, prefixed `builder-reference:` or `guide-check:`; the
`guide-check` summary goes to stdout.
"""

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
from urllib.parse import unquote
from pathlib import Path

GUIDE = "docs/builders"
REFERENCE = "docs/builders/reference.md"
ERRORS = "docs/specs/content-language/v1/errors.md"
# From docs/builders/, the heading `## 3. The codes` in errors.md.
ERRORS_LINK = "../specs/content-language/v1/errors.md#3-the-codes"
GENERATED = ("<!-- GENERATED by make builder-reference from `andara-cli content reference --output json`. "
             "DO NOT HAND-EDIT. -->")


class Fail(Exception):
    """A finding that ends the run: printed as `<prefix>: <message>`, exit 1."""


def run(cmd, env=None, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, env=env, **kw)


def build_cli(root, tmp):
    out = os.path.join(tmp, "andara-cli")
    r = run([os.environ.get("GO", "go"), "build", "-o", out, "./cmd/andara-cli"], cwd=root)
    if r.returncode != 0:
        raise Fail("go build ./cmd/andara-cli failed: " + r.stderr.strip()[-400:])
    return out


def clean_env(tmp):
    home = os.path.join(tmp, "home")
    os.makedirs(home, exist_ok=True)
    return {"PATH": os.environ.get("PATH", ""), "HOME": home, "XDG_CONFIG_HOME": home,
            "XDG_STATE_HOME": home, "NO_COLOR": "1"}


# --- builder-reference -------------------------------------------------------------------

def reference_json(cli, env):
    r = run([cli, "content", "reference", "--output", "json"], env=env)
    if r.returncode != 0:
        raise Fail("`andara-cli content reference --output json` exited %d: %s"
                   % (r.returncode, r.stderr.strip()[-400:]))
    try:
        data = json.loads(r.stdout)
    except ValueError as e:
        raise Fail("`content reference` printed no JSON object: %s" % e)
    if not isinstance(data, dict):
        raise Fail("`content reference` printed JSON that isn't an object")
    version = data.get("format_version")
    if type(version) is not int or version != 1:
        raise Fail("unsupported format_version %s" % json.dumps(version))
    for key in ("directions", "component_types", "core", "diagnostics"):
        if key not in data:
            raise Fail("`content reference` JSON has no %r" % key)
    return data


def render_reference(data):
    """The four sections, in the JSON's order. Unknown keys are ignored (AC-4)."""
    core = data["core"]
    out = [GENERATED, "", "# Reference", "",
           "[← The Builder's Guide](README.md)", "",
           "## Directions", "",
           "| Direction | Reverse |", "|-----------|---------|"]
    for d in data["directions"]:
        out.append("| `%s` | `%s` |" % (d["name"], d["reverse"]))
    out += ["", "## Component types", "", "| Type | Field | Kind |", "|------|-------|------|"]
    for c in data["component_types"]:
        fields = c.get("fields") or []
        if not fields:
            out.append("| `%s` | none | none |" % c["type"])
        for f in fields:
            out.append("| `%s` | `%s` | %s |" % (c["type"], f["name"], f["kind"]))
    out += ["", "## `%s@%s` Templates" % (core["pack"], core["version"]), "",
            "| Template | Kind | Chain |", "|----------|------|-------|"]
    for t in core["templates"]:
        out.append("| `%s` | %s | %s |" % (t["name"], t["kind"], " › ".join("`%s`" % n for n in t["chain"])))
    out += ["", "## Diagnostics", "", "| Code | Severity | Raised by |", "|------|----------|-----------|"]
    for d in data["diagnostics"]:
        out.append("| [`%s`](%s) | %s | %s |" % (d["code"], ERRORS_LINK, d["severity"], d["raised_by"]))
    return "\n".join(out) + "\n"


def cmd_reference(root, cli, tmp, check):
    cli = cli or build_cli(root, tmp)
    text = render_reference(reference_json(cli, clean_env(tmp)))
    path = Path(root, REFERENCE)
    if check:
        if not path.exists() or path.read_text() != text:
            raise Fail("stale; run make builder-reference")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print("builder-reference: wrote %s" % REFERENCE)
    return 0


# --- guide-check -------------------------------------------------------------------------

FENCE_OPEN = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")
INLINE_LINK = re.compile(r"\[(?:[^\[\]]|\[[^\]]*\])*\]\(\s*(<[^>]*>|(?:[^()\s]|\([^()\s]*\))+)(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)")
REF_DEF = re.compile(r"^ {0,3}\[[^\]]+\]:\s*(<[^>]*>|\S+)")
HREF = re.compile(r"""<a\s[^>]*?href=["']([^"']+)["']""", re.I)
SCHEME = re.compile(r"^([a-z][a-z0-9+.-]*:|//)", re.I)
CODE_ROW = re.compile(r"^\|\s*(?:\[)?`([a-z][a-z0-9_]*)`")


def md_files(guide):
    return sorted(p for p in Path(guide).rglob("*.md"))


def split_blocks(text):
    """(code lines, prose lines, line of an unclosed fence or 0), 1-based numbers.

    CommonMark: a fence closes on a run of the same character at least as long as the opener,
    with nothing after it, so a longer fence may contain a shorter one.
    """
    code, prose, fence, opened = [], [], None, 0
    for n, line in enumerate(text.splitlines(), 1):
        if fence is None:
            m = FENCE_OPEN.match(line)
            if m and not (m.group(1)[0] == "`" and "`" in m.group(2)):
                fence, opened = m.group(1), n
                continue
            prose.append((n, line))
        else:
            stripped = line.strip()
            if stripped and set(stripped) == {fence[0]} and len(stripped) >= len(fence) and len(line) - len(line.lstrip()) < 4:
                fence = None
                continue
            code.append((n, line))
    return code, prose, (opened if fence else 0)


def joined_commands(code_lines):
    """`andara-cli …` lines, with backslash continuations joined; the first line's number."""
    out, i = [], 0
    while i < len(code_lines):
        n, line = code_lines[i]
        text = line.strip()
        text = text[2:].lstrip() if text.startswith("$ ") else text
        if text.startswith("andara-cli ") or text == "andara-cli":
            while text.endswith("\\") and i + 1 < len(code_lines):
                i += 1
                text = text[:-1].rstrip() + " " + code_lines[i][1].strip()
            out.append((n, text))
        i += 1
    return out


class Completer:
    def __init__(self, cli, env):
        self.cli, self.env, self.cache = cli, env, {}

    def ask(self, words, to_complete):
        key = (tuple(words), to_complete)
        if key not in self.cache:
            r = run([self.cli, "__complete", *words, to_complete], env=self.env)
            names = []
            for line in r.stdout.splitlines():
                if line.startswith(":"):
                    break
                names.append(line.split("\t")[0])
            self.cache[key] = names
        return self.cache[key]

    def resolve(self, words):
        """(path, first unresolved word or None, positional leftovers, is_group)."""
        path, consumed, leftover = [], [], []
        ctx = []
        ended = False
        for w in words:
            if w.startswith("-"):
                consumed.append(w)
                continue
            # A command context lists flags for "-"; a pending flag value doesn't, so the word
            # is that flag's value, not a subcommand or a positional.
            if not any(c.startswith("-") for c in self.ask(consumed, "-")):
                consumed.append(w)
                continue
            if not ended and w in self.ask(consumed, ""):
                path.append(w)
                consumed.append(w)
                continue
            if not ended:
                ctx = list(consumed)  # the command the path resolved to, with its flags
            ended = True
            leftover.append(w)
            consumed.append(w)
        group = bool(leftover) and bool(self.ask(ctx, ""))
        return path, (leftover[0] if leftover else None), leftover, group


def check_command(comp, cli, env, words):
    """None when the line is fine, else the words that name the missing command."""
    path, first_bad, leftover, group = comp.resolve(words)
    if group and leftover:
        return ["andara-cli", *path, first_bad]
    r = run([cli, *path, "--help"], env=env)
    if r.returncode != 0:
        return ["andara-cli", *path]
    return None


def slug(heading, seen):
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", heading)  # link syntax: the text stays
    s = re.sub(r"[`*]", "", s.strip().lower())
    s = re.sub(r"[^\w\- ]", "", s).replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else "%s-%d" % (s, n)


def anchors(path):
    """Lowercased anchors GitHub generates for a file: ATX and setext headings, and explicit
    <a id=…> / <a name=…>. Matching is case-insensitive, as GitHub's is."""
    _, prose, _ = split_blocks(Path(path).read_text())
    seen, out = {}, set()
    for i, (_, line) in enumerate(prose):
        out.update(a.lower() for a in re.findall(r'<a\s+(?:id|name)="([^"]+)"', line))
        m = re.match(r"^ {0,3}#{1,6}\s+(.*?)\s*#*\s*$", line)
        if not m and i + 1 < len(prose) and line.strip() and re.match(r"^ {0,3}(=+|-+)\s*$", prose[i + 1][1]):
            m = re.match(r"^\s*(.*?)\s*$", line)
        if m:
            out.add(slug(re.sub(r"<[^>]+>", "", m.group(1)), seen))
    return out


def link_targets(line):
    """Every link destination on a prose line: inline links and images, reference definitions,
    and <a href>. Inline code is removed first."""
    line = re.sub(r"`[^`]*`", "", line)
    found = [m.group(1) for m in INLINE_LINK.finditer(line)]
    m = REF_DEF.match(line)
    if m:
        found.append(m.group(1))
    found += HREF.findall(line)
    return found


def resolve_link(root, f, target):
    """(destination Path, fragment) for a relative link, or None for one that isn't ours to check."""
    target = unquote(target.strip().strip("<>").strip())
    target = re.sub(r"\\([\\`*_{}\[\]()#+\-.!<>|])", r"\1", target)
    if not target or SCHEME.match(target):
        return None
    path, _, frag = target.partition("#")
    path = path.partition("?")[0]
    if not path:
        return f, frag
    base = Path(root) if path.startswith("/") else f.parent
    return (base / path.lstrip("/")), frag


def errors_codes(path):
    codes, in_codes = [], False
    for line in Path(path).read_text().splitlines():
        if line.startswith("## "):
            in_codes = line.startswith("## 3.")
            continue
        if in_codes:
            m = CODE_ROW.match(line)
            if m:
                codes.append(m.group(1))
    return codes


def reference_codes(path):
    codes, in_diag = [], False
    for line in Path(path).read_text().splitlines():
        if line.startswith("## "):
            in_diag = line.strip() == "## Diagnostics"
            continue
        if in_diag:
            m = CODE_ROW.match(line)
            if m:
                codes.append(m.group(1))
    return codes


def command_words(text):
    """The words of an `andara-cli …` line after the program name, up to the first shell operator
    (`|`, `>`, `&&`, `;`) or comment."""
    lex = shlex.shlex(text, posix=True, punctuation_chars=True)
    lex.whitespace_split, lex.commenters = True, "#"
    words = []
    try:
        for tok in lex:
            if set(tok) <= set(lex.punctuation_chars):
                break
            words.append(tok)
    except ValueError:  # an unbalanced quote: take the words as written
        words = text.split()
    return words[1:]


def cmd_guide_check(root, cli, tmp):
    guide = Path(root, GUIDE)
    if not guide.is_dir():
        print("guide-check: %s doesn't exist" % GUIDE, file=sys.stderr)
        return 2
    findings = []
    files = md_files(guide)
    commands = links = 0
    cli_ready = None
    root_path = Path(root).resolve()

    for f in files:
        rel = f.relative_to(root)
        code, prose, unclosed = split_blocks(f.read_text())
        if unclosed:
            findings.append("%s:%d: unclosed code fence" % (rel, unclosed))
        for n, text in joined_commands(code):
            if cli_ready is None:
                cli = cli or build_cli(root, tmp)
                cli_ready = (Completer(cli, clean_env(tmp)), clean_env(tmp))
            commands += 1
            bad = check_command(cli_ready[0], cli, cli_ready[1], command_words(text))
            if bad:
                findings.append('%s:%d: no command "%s"' % (rel, n, " ".join(bad)))
        for n, line in prose:
            for target in link_targets(line):
                resolved = resolve_link(root, f, target)
                if resolved is None:
                    continue
                links += 1
                dest, frag = resolved
                ok = dest.exists() and dest.resolve().is_relative_to(root_path)
                if ok and frag:
                    # A fragment needs a Markdown file with that anchor; on a directory or any
                    # other file nothing could match it.
                    ok = dest.is_file() and dest.suffix == ".md" and frag.lower() in anchors(dest)
                if not ok:
                    findings.append("%s:%d: broken link %s" % (rel, n, target))

    codes = 0
    ref, errs = Path(root, REFERENCE), Path(root, ERRORS)
    if ref.exists():
        if not errs.exists():
            findings.append("%s not found, so the reference's codes can't be checked" % ERRORS)
        else:
            in_ref, in_err = set(reference_codes(ref)), set(errors_codes(errs))
            codes = len(in_ref | in_err)
            for c in sorted(in_err - in_ref):
                findings.append("code %s is in errors.md but not the reference" % c)
            for c in sorted(in_ref - in_err):
                findings.append("code %s is in the reference but not errors.md" % c)
    elif files:
        # An empty guide passes (AC-9). One with pages and no reference has nothing to hold the
        # codes against, which is the check going quiet, not passing.
        findings.append("%s not found; run make builder-reference" % REFERENCE)

    for line in findings:
        print("guide-check: " + line, file=sys.stderr)
    if findings:
        return 1
    print("guide-check: %d commands, %d codes, %d links ok" % (commands, codes, links))
    return 0


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("action", choices=["reference", "reference-check", "guide-check"])
    ap.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    ap.add_argument("--cli", help="an andara-cli to use instead of building one (tests)")
    a = ap.parse_args(argv)
    prefix = "guide-check" if a.action == "guide-check" else "builder-reference"
    with tempfile.TemporaryDirectory() as tmp:
        try:
            if a.action == "guide-check":
                return cmd_guide_check(a.root, a.cli, tmp)
            return cmd_reference(a.root, a.cli, tmp, check=(a.action == "reference-check"))
        except Fail as e:
            print("%s: %s" % (prefix, e), file=sys.stderr)
            return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
