#!/usr/bin/env python3
"""Regenerate BACKLOG.md from docs/stories/*.md frontmatter.

Deterministic: same inputs produce byte-identical output. `--check` verifies the
committed file is current and exits 1 if it is stale.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from andara_docs import BACKLOG, EPICS_DIR, load_dir, load_stories, rel  # noqa: E402

STATUS_ORDER = ["blocked", "review", "in-progress", "ready", "draft", "done"]
ADR_RE = re.compile(r"\bADR-\d{4}\b")
BLOCKED_BY_RE = re.compile(
    r"^##\s+Blocked by\s*$(.*?)(?=^##\s|\Z)", re.MULTILINE | re.DOTALL
)
HEADER = (
    "<!-- GENERATED by `make backlog` from docs/stories/*.md frontmatter. "
    "DO NOT HAND-EDIT. -->\n"
)


def render():
    stories = load_stories()
    epics = {d.get("id"): d for _, d, _, _ in load_dir(EPICS_DIR)}
    rows = []
    gates = {}
    for path, d, _, body in stories:
        rows.append((d, rel(path)))
        # A blocked story states its gate in a "## Blocked by" section. Read the ADRs
        # from there rather than guessing from depends_on, which answers a different
        # question — sequencing, not what is actually holding the story.
        m = BLOCKED_BY_RE.search(body)
        gates[d.get("id")] = sorted(set(ADR_RE.findall(m.group(1)))) if m else []

    def key(item):
        d = item[0]
        status = d.get("status", "draft")
        rank = STATUS_ORDER.index(status) if status in STATUS_ORDER else len(STATUS_ORDER)
        return (rank, d.get("id", ""))

    out = [HEADER, "\n# Backlog — Andara's World\n\n"]
    out.append(
        "Generated view of `docs/stories/`. Story status lives in frontmatter; files never move.\n"
        "Run `make backlog` after any story change. `make check` fails if this file is stale.\n\n"
    )

    counts = {}
    for d, _ in rows:
        counts[d.get("status", "draft")] = counts.get(d.get("status", "draft"), 0) + 1
    out.append("## Summary\n\n")
    out.append("| Status | Count |\n|--------|-------|\n")
    for s in STATUS_ORDER:
        if s in counts:
            out.append("| `%s` | %d |\n" % (s, counts[s]))
    out.append("| **total** | **%d** |\n\n" % len(rows))

    out.append("## Attention first\n\n")
    attn = [r for r in rows if r[0].get("status") in ("blocked", "review")]
    if attn:
        out.append("| ID | Status | Title | Blocked by / awaiting |\n")
        out.append("|----|--------|-------|------------------------|\n")
        for d, path in sorted(attn, key=key):
            note = "—"
            if d.get("status") == "blocked":
                g = gates.get(d.get("id")) or []
                note = ", ".join("`%s`" % x for x in g) if g else "see story header"
            elif d.get("status") == "review":
                note = "review by brian"
            out.append(
                "| [`%s`](%s) | `%s` | %s | %s |\n"
                % (d.get("id"), path, d.get("status"), d.get("title"), note)
            )
    else:
        out.append("Nothing blocked or in review.\n")
    out.append("\n")

    out.append("## By status\n\n")
    for status in STATUS_ORDER:
        group = [r for r in rows if r[0].get("status") == status]
        if not group:
            continue
        out.append("### `%s` (%d)\n\n" % (status, len(group)))
        out.append("| ID | Epic | Component | Size | Risk | Assignee | Title | Depends on |\n")
        out.append("|----|------|-----------|------|------|----------|-------|------------|\n")
        for d, path in sorted(group, key=lambda r: r[0].get("id", "")):
            deps = ", ".join("`%s`" % x for x in (d.get("depends_on") or [])) or "—"
            out.append(
                "| [`%s`](%s) | `%s` | %s | %s | %s | %s | %s | %s |\n"
                % (
                    d.get("id"), path, d.get("epic"), d.get("component"), d.get("size"),
                    d.get("risk"), d.get("assignee"), d.get("title"), deps,
                )
            )
        out.append("\n")

    out.append("## By epic\n\n")
    seen_epics = sorted({d.get("epic") for d, _ in rows if d.get("epic")})
    for eid in seen_epics:
        e = epics.get(eid, {})
        out.append("### `%s` — %s\n\n" % (eid, e.get("title", "(unknown epic)")))
        gates = e.get("adr_gates") or []
        refs = e.get("adr_refs") or []
        out.append(
            "Milestone `%s` · status `%s` · ADR gates: %s · constrained by: %s\n\n"
            % (
                e.get("milestone", "—"),
                e.get("status", "—"),
                ", ".join("`%s`" % g for g in gates) if gates else "none",
                ", ".join("`%s`" % r for r in refs) if refs else "—",
            )
        )
        out.append("| ID | Status | Title |\n|----|--------|-------|\n")
        for d, path in sorted((r for r in rows if r[0].get("epic") == eid),
                              key=lambda r: r[0].get("id", "")):
            out.append(
                "| [`%s`](%s) | `%s` | %s |\n" % (d.get("id"), path, d.get("status"), d.get("title"))
            )
        out.append("\n")

    return "".join(out)


def main():
    text = render()
    if "--check" in sys.argv:
        current = ""
        if os.path.exists(BACKLOG):
            with open(BACKLOG, "r", encoding="utf-8") as fh:
                current = fh.read()
        if current != text:
            sys.stderr.write(
                "backlog: BACKLOG.md is stale relative to docs/stories/ (run `make backlog`)\n"
            )
            return 1
        print("backlog: BACKLOG.md is current")
        return 0
    with open(BACKLOG, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("backlog: wrote %s" % BACKLOG)
    return 0


if __name__ == "__main__":
    sys.exit(main())
