#!/usr/bin/env python3
"""Regenerate docs/status.md — the two-lane development state, one screen.

The question this answers is not "what is in the backlog" (BACKLOG.md answers that).
It is "what do I prompt next in each lane, and what am I holding up by not deciding".

Hard budget: 50 lines, 100 columns. The generator refuses to emit more, because a
status report that scrolls is a status report nobody reads. When it refuses, the fix
is to close something, not to raise the budget.

Deterministic: same docs produce byte-identical output, so `--check` can gate CI. Git
state is deliberately not read — story frontmatter is the record, and drift between
frontmatter and branches is a discipline problem that a generator must not paper over.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from andara_docs import ADR_DIR, REPO, load_dir, load_stories, die  # noqa: E402

STATUS = os.path.join(REPO, "docs", "status.md")
MAX_LINES = 50
MAX_COLS = 100

HEADER = (
    "<!-- GENERATED by `make status` from docs/stories/ and docs/adr/. DO NOT HAND-EDIT. -->\n"
)

# A dependency is satisfied when its code is on main. `review` counts: the branch merged,
# only the §8 checklist is outstanding. `in-progress` does not count — depending on
# unmerged work is how two lanes deadlock.
SATISFIED = ("done", "review")

LANES = [
    ("claude-code", "Architecture", "specs, ADRs, infra, automation"),
    ("cursor", "Implementation", "server and cli source, tests"),
]

# Only list items. ADR-0008 mentions the tag in prose ("the largest `[NEEDS BRIAN]` in the
# repo"); pulling that in would render half a sentence as if it were a question.
NEEDS_RE = re.compile(r"^\s*[-*]\s+.*?\[NEEDS BRIAN\]`?\s*(.*)")
SLUG_RE = re.compile(r"^AW-[A-Z]+-\d{3}-(.*)\.md$")


def clean(text):
    """Strip the markdown a terminal will not render."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def fit(text, width):
    text = clean(text)
    return text if len(text) <= width else text[: width - 1].rstrip() + "…"


def needs_brian(body):
    """Pull the `[NEEDS BRIAN]` items out of a doc, joining wrapped continuation lines."""
    out = []
    lines = body.split("\n")
    for i, line in enumerate(lines):
        m = NEEDS_RE.search(line)
        if not m:
            continue
        text = m.group(1).lstrip("` ")
        for cont in lines[i + 1:]:
            if not cont.startswith(("  ", "\t")) or not cont.strip():
                break
            if cont.lstrip().startswith(("-", "*")):
                break
            text += " " + cont.strip()
        # These items are written as "**The question?** followed by rationale". The
        # question is what belongs on one line of a status report; the rationale is
        # what the story is for.
        lead = re.match(r"\s*\*\*(.+?)\*\*", text)
        out.append(clean(lead.group(1) if lead else text))
    return out


def branch_for(path, story_id):
    m = SLUG_RE.match(os.path.basename(path))
    return "%s-%s" % (story_id.lower(), m.group(1)) if m else story_id.lower()


def render():
    stories = []
    for path, d, _, body in load_stories():
        d = dict(d)
        d["_path"] = path
        d["_needs"] = needs_brian(body)
        stories.append(d)
    by_id = {d["id"]: d for d in stories}

    def satisfied(d):
        return all(by_id.get(x, {}).get("status") in SATISFIED for x in d.get("depends_on", []))

    # The critical path, for free: a story that unblocks five others outranks one that
    # unblocks none, regardless of what order they were written in.
    def rank(d):
        return (-len(d.get("blocks", [])), d["id"])

    counts = {}
    for d in stories:
        counts[d.get("status", "draft")] = counts.get(d.get("status", "draft"), 0) + 1

    out = [HEADER, "\n# Status — Andara's World\n\n"]
    tally = " · ".join(
        "%d %s" % (counts[s], s)
        for s in ("in-progress", "review", "ready", "draft", "blocked", "done")
        if counts.get(s)
    )
    out.append("%d stories — %s\n" % (len(stories), tally))
    out.append("Regenerate with `make status`; `make check` fails if this file is stale.\n")

    surfaced = []
    for assignee, lane, scope in LANES:
        mine = [d for d in stories if d.get("assignee") == assignee]
        now = sorted([d for d in mine if d.get("status") == "in-progress"], key=rank)
        review = sorted([d for d in mine if d.get("status") == "review"], key=rank)
        ready = sorted([d for d in mine if d.get("status") == "ready" and satisfied(d)], key=rank)
        held = [d for d in mine if d.get("status") == "ready" and not satisfied(d)]

        # Grooming a draft IS the architecture lane's work, so a draft is a legitimate
        # next item there. Cursor never picks up a draft — it has no contract to build to.
        if assignee == "claude-code" and not ready:
            ready = sorted([d for d in mine if d.get("status") == "draft"], key=rank)[:1]

        out.append("\n## %s lane — %s · %s\n\n" % (lane, assignee, scope))

        for d in now[:1]:
            out.append("  now    %s  %s\n" % (d["id"], fit(d["title"], 79)))
            if assignee == "cursor":
                out.append("         branch %s\n" % branch_for(d["_path"], d["id"]))
            surfaced.append(d)
        if not now:
            out.append("  now    — nothing in flight\n")

        for d in ready[:2]:
            gates = len(d.get("blocks", []))
            tag = "  (unblocks %d)" % gates if gates else ""
            out.append(
                "  next   %s  %s%s\n"
                % (d["id"], fit(d["title"], 76 - len(tag)), tag)
            )
            surfaced.append(d)
        if not ready:
            out.append("  next   — nothing groomed and unblocked\n")

        if review:
            ids = ", ".join(d["id"] for d in review)
            out.append("  review %s\n" % fit("%s — run the §8 checklist, then flip to done" % ids, 84))
            surfaced.extend(review)
        if held:
            ids = ", ".join(d["id"] for d in sorted(held, key=rank))
            out.append("  held   %s\n" % fit("%d groomed, blocked by unmerged work: %s" % (len(held), ids), 84))

    # Decisions. Only the ones attached to something live: a proposed ADR, or a story
    # one of the lanes is about to touch. The rest are real but not urgent, and a report
    # that lists all forty is one nobody acts on.
    adrs = [(d, body) for _, d, _, body in load_dir(ADR_DIR)]
    pending = []
    for d, body in sorted(adrs, key=lambda x: x[0].get("id", "")):
        if d.get("status") != "proposed":
            continue
        qs = needs_brian(body)
        if not qs:
            pending.append((d["id"], "proposed, unaccepted — %s" % d.get("title", "")))
        for q in qs:
            pending.append((d["id"], q))
    live = {d["id"]: d for d in surfaced}
    for sid in sorted(live):
        for q in live[sid]["_needs"]:
            pending.append((sid, q))

    total_open = sum(len(needs_brian(b)) for _, b in adrs) + sum(len(d["_needs"]) for d in stories)
    out.append("\n## Decisions the lanes are waiting on\n\n")
    if pending:
        for who, q in pending[:9]:
            out.append("  %-11s %s\n" % (who, fit(q, 84)))
        rest = total_open - len(pending[:9])
        if rest > 0:
            out.append(
                "  %-11s %d more, attached to stories neither lane has reached\n" % ("", rest)
            )
    else:
        out.append("  none — every open question is on a story neither lane has reached\n")

    out.append(
        "\nLegend: `now` is in flight · `next` is groomed with every dependency merged ·\n"
        "`held` is groomed but waiting · a dependency counts as met at `review`, not at merge-to-branch.\n"
    )
    return "".join(out)


def main():
    text = render()
    lines = text.split("\n")
    if len(lines) - 1 > MAX_LINES:
        die(
            "status: rendered %d lines, budget is %d. Close something or shorten a title;\n"
            "        do not raise the budget — the one-screen constraint is the point."
            % (len(lines) - 1, MAX_LINES)
        )
    wide = [(i + 1, l) for i, l in enumerate(lines) if len(l) > MAX_COLS]
    if wide:
        die("status: line %d is %d columns, budget is %d" % (wide[0][0], len(wide[0][1]), MAX_COLS))

    if "--check" in sys.argv:
        try:
            with open(STATUS, "r", encoding="utf-8") as fh:
                current = fh.read()
        except FileNotFoundError:
            die("status: docs/status.md does not exist. Run `make status`.")
        if current != text:
            die("status: docs/status.md is stale. Run `make status` and commit the result.")
        sys.stderr.write("status: docs/status.md is current\n")
        return
    with open(STATUS, "w", encoding="utf-8") as fh:
        fh.write(text)
    sys.stderr.write("status: wrote docs/status.md (%d lines)\n" % (len(lines) - 1))


if __name__ == "__main__":
    main()
