#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Valesor Development

"""Generate the chart's values.schema.json and templates/_env.tpl from keys.yaml (AW-INF-003).

Two inputs, both under deploy/helm/andara:

  keys.yaml         the server configuration key registry — dotted key, env name, type,
                    default, owning story
  schema.base.yaml  the hand-written schema for everything that is NOT a server key
                    (replicaCount, image, probes, volumes, ...)

Two outputs, committed and diffed by `make check`:

  values.schema.json   schema.base.yaml with `properties.server` filled in from every key
                       whose env the server code actually reads. additionalProperties is
                       false at every level, so a values file cannot set a key the running
                       binary would ignore.
  templates/_env.tpl   one `- name: ANDARA_X` / `value:` block per in-code key, emitted only
                       when the value is set, so the chart never re-states a server default.

The code is the authority for which keys exist. `--check` fails on an ANDARA_* literal in
server/**/*.go that keys.yaml does not list (an operator could not set it), warns on a
keys.yaml entry the code does not read yet (groomed, not built), and fails if either
generated file is stale.
"""
import argparse
import glob
import json
import os
import re
import sys

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHART = os.path.join(REPO, "deploy", "helm", "andara")
KEYS = os.path.join(CHART, "keys.yaml")
BASE = os.path.join(CHART, "schema.base.yaml")
SCHEMA = os.path.join(CHART, "values.schema.json")
ENV_TPL = os.path.join(CHART, "templates", "_env.tpl")
CODE_GLOBS = [os.path.join(REPO, "server", "**", "*.go")]

ENV_RE = re.compile(r"\bANDARA_[A-Z0-9_]+\b")
DURATION_PATTERN = r"^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$"


def rel(p):
    return os.path.relpath(p, REPO)


def load_registry():
    with open(KEYS) as f:
        doc = yaml.safe_load(f)
    keys = doc.get("keys") or []
    seen_key, seen_env = {}, {}
    for k in keys:
        for field in ("key", "env", "type", "story"):
            if field not in k:
                sys.exit("values-schema: %s: entry %r lacks %r" % (rel(KEYS), k, field))
        if k["type"] not in ("string", "int", "number", "bool", "duration", "enum"):
            sys.exit("values-schema: %s: %s has unknown type %r" % (rel(KEYS), k["key"], k["type"]))
        if k["type"] == "enum" and not k.get("values"):
            sys.exit("values-schema: %s: enum %s has no values" % (rel(KEYS), k["key"]))
        if k["key"] in seen_key:
            sys.exit("values-schema: %s: duplicate key %s" % (rel(KEYS), k["key"]))
        if k["env"] in seen_env:
            sys.exit("values-schema: %s: duplicate env %s" % (rel(KEYS), k["env"]))
        seen_key[k["key"]] = k
        seen_env[k["env"]] = k
    return keys, set(doc.get("ignore_env") or [])


def code_envs():
    found = {}
    for pattern in CODE_GLOBS:
        for path in glob.glob(pattern, recursive=True):
            if path.endswith("_test.go"):
                continue
            with open(path) as f:
                for name in ENV_RE.findall(f.read()):
                    found.setdefault(name, rel(path))
    return found


def prop_for(k):
    t = k["type"]
    desc = "%s (%s). Default when unset: %r." % (k["env"], k["story"], k.get("default"))
    if t == "string":
        p = {"type": "string"}
    elif t in ("int", "number"):
        p = {"type": "integer" if t == "int" else "number"}
        if "min" in k:
            p["minimum"] = k["min"]
        if "max" in k:
            p["maximum"] = k["max"]
    elif t == "bool":
        p = {"type": "boolean"}
    elif t == "duration":
        p = {"type": "string", "pattern": DURATION_PATTERN}
    else:
        p = {"type": "string", "enum": list(k["values"])}
    p["description"] = desc
    return p


def server_schema(keys):
    root = {"type": "object", "additionalProperties": False, "properties": {}}
    for k in keys:
        node = root
        parts = k["key"].split(".")
        for part in parts[:-1]:
            node = node["properties"].setdefault(
                part, {"type": "object", "additionalProperties": False, "properties": {}}
            )
        node["properties"][parts[-1]] = prop_for(k)
    return root


def render_schema(keys):
    with open(BASE) as f:
        base = yaml.safe_load(f)
    base.setdefault("properties", {})["server"] = server_schema(keys)
    return json.dumps(base, indent=2, sort_keys=False) + "\n"


def render_env_tpl(keys):
    out = [
        "{{- /*",
        "GENERATED by `make values-schema` from keys.yaml. DO NOT HAND-EDIT.",
        "",
        "ConfigMap data: one ANDARA_* line per server configuration key the running binary",
        "reads, emitted only when the values file sets it. A key that is not set is not",
        "rendered, so the server default applies and the chart never restates it (AW-INF-003).",
        "*/ -}}",
        '{{- define "andara.serverEnv" -}}',
    ]
    for k in keys:
        parts = k["key"].split(".")
        dig = " ".join('"%s"' % p for p in parts)
        out.append('{{- $v := dig %s "__unset__" (.Values.server | default dict) }}' % dig)
        out.append('{{- if not (eq (toString $v) "__unset__") }}')
        out.append("%s: {{ $v | toString | quote }}" % k["env"])
        out.append("{{- end }}")
    out.append("{{- end -}}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify outputs are current; never write")
    ap.add_argument("--verbose", action="store_true", help="list every pending key")
    args = ap.parse_args()

    keys, ignore = load_registry()
    in_code = code_envs()
    by_env = {k["env"]: k for k in keys}

    failures = []
    for env, path in sorted(in_code.items()):
        if env in ignore or env in by_env:
            continue
        failures.append(
            "%s reads %s but %s does not list it — add a key entry so the chart can set it"
            % (path, env, rel(KEYS))
        )
    pending = [k for k in keys if k["env"] not in in_code]
    active = [k for k in keys if k["env"] in in_code]
    if pending:
        # One line, grouped by story: this list is long by design until the stories land,
        # and seventy warnings on every `make check` would train everyone to ignore them.
        by_story = {}
        for k in pending:
            by_story.setdefault(k["story"], []).append(k["key"])
        summary = ", ".join("%s: %d" % (st, len(ks)) for st, ks in sorted(by_story.items()))
        print("values-schema: warn: %d groomed key(s) not read by the server yet, left out of "
              "the schema (%s); `--verbose` lists them" % (len(pending), summary))
        if args.verbose:
            for k in pending:
                print("  %s (%s) — %s" % (k["key"], k["env"], k["story"]))

    schema = render_schema(active)
    tpl = render_env_tpl(active)

    if failures:
        for f in failures:
            print("values-schema: " + f, file=sys.stderr)
        sys.exit(1)

    if args.check:
        stale = []
        for path, want in ((SCHEMA, schema), (ENV_TPL, tpl)):
            have = open(path).read() if os.path.exists(path) else None
            if have != want:
                stale.append(rel(path))
        if stale:
            print("values-schema: stale: %s (run `make values-schema`)" % ", ".join(stale),
                  file=sys.stderr)
            sys.exit(1)
        print("values-schema: %d key(s) in schema, %d pending; outputs current"
              % (len(active), len(pending)))
        return

    with open(SCHEMA, "w") as f:
        f.write(schema)
    with open(ENV_TPL, "w") as f:
        f.write(tpl)
    print("values-schema: wrote %s and %s (%d key(s) in schema, %d pending)"
          % (rel(SCHEMA), rel(ENV_TPL), len(active), len(pending)))


if __name__ == "__main__":
    main()
